before_script:
  - date
  - uname -a
  - printenv | sort

stages:
  - frontend_test 
  - backend_test
  - api_test

frontend_test:
  stage: frontend_test
  image: node:latest
  script:
    - cd frontend
    - cd empoweringknowledge
    - npm i npm@latest -g
    #- chmod a+x app/node_modules/.bin/react-scripts
    - npm i -g mocha
    #- npm test

backend_test:
  stage: backend_test
  image: python
  script:
    - pip install requests
    - pip install pandas 
    - cd backend
    - python tests.py

api_test:
  stage: api_test
  image: 
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run Postman.json
